# Utilise une image Python légère basée sur 3.11
FROM python:3.11-slim

# Définit le répertoire de travail
WORKDIR /app

# Copie du fichier requirements.txt
COPY requirements.txt ./

# Met à jour pip et installe les dépendances
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# Copie du code de l'application
COPY . /app

# Expose le port Streamlit par défaut
EXPOSE 8501

# Comnde par défaut pour lancer l'application
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
