# Utilise une image Python légère
FROM python:3.9-slim

# Définit le répertoire de travail
WORKDIR /app

# Copie du fichier requirements.txt
COPY requirements.txt ./

# Installation des dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copie du code de l'application
COPY . /app

# Expose le port Streamlit par défaut
EXPOSE 8501

# Command par défaut pour lancer l'application
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]