
FROM python:3.10
WORKDIR /app
COPY . /app
RUN pip install --trusted-host pypi.python.org -r requirements.txt
# Installation de Google Chrome
RUN apt-get update && apt-get install -y wget unzip && \
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt install -y ./google-chrome-stable_current_amd64.deb && \
    rm google-chrome-stable_current_amd64.deb

# Étape 5 : Créer les répertoires nécessaires à l'exécution (si tu ne veux pas les créer dynamiquement)
RUN mkdir -p data/raw/annuel data/raw/calendar data/processed models

# Étape 6 : Définir le script principal à exécuter
CMD ["python", "main.py"]
