FROM python:3.10-slim

# 1. Variables d’environnement
ENV PYTHONUNBUFFERED=1 \
    BACKEND_STORE_URI=sqlite:///mlflow.db \
    ARTIFACT_ROOT=/app/artifacts \
    MLFLOW_TRACKING_URI=http://127.0.0.1:5000 \
    # On passe des options à Gunicorn pour MLflow
    GUNICORN_CMD_ARGS="--timeout 120 --workers 2"

WORKDIR /app

# 2. Installer les dépendances Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 3. Copier le code
COPY . /app

# 4. Créer les répertoires pour MLflow
RUN mkdir -p /app/artifacts

# 5. Exposer le port MLflow
EXPOSE 5000

# 6. Copier et rendre exécutable l’entrypoint
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
